p1-b1-r18 Paris
scta-texts/bHY6yh pull request #132
Opened 2023-06-01 20:04 UTC by GrantSchreib

2023-06-03 10:56 UTC, jeffreycwitt requested changes
Looking good. Take a look at my note about the placement of page breaks and column breaks.

2023-06-03 10:56 UTC, jeffreycwitt commented on bHY6yh-de4661/cod-bxxqqq_bHY6yh-de4661.xml
> +            <p xml:id="bHY6yh-de4661-d1e133">
page breaks and columns breaks always need to be inside a `<p>` tag. See my adjustment below.

```suggestion
            </p>
            <p xml:id="bHY6yh-de4661-d1e133">
              <pb ed="#B" n="8-v"/>
              <cb ed="#B" n="a"/>

```

2023-06-04 19:00 UTC, GrantSchreib commented
corrected

2023-06-09 21:31 UTC, jeffreycwitt approved these changes
looks good.

2023-06-09 21:31 UTC, merged