p4-b6-r3 Vatican
scta-texts/bHY6yh pull request #1783
Opened 2024-09-07 18:25 UTC by GrantSchreib

2024-09-28 14:10 UTC, jeffreycwitt requested changes
Great job. especially with the line breaks at the beginning of the rubric. That's exactly how it should be done!

Just a few minor changes.

2024-09-28 14:10 UTC, jeffreycwitt commented on bHY6yh-d90266/cod-yyyiou_bHY6yh-d90266.xml
> +              ¶ <ref xml:id="bHY6yh-d90266-Rd1e134">Tobias capitulo VI</ref> <quote xml:id="bHY6yh-d90266-Qd1e139">Hii qui
```suggestion
              ¶ <ref xml:id="bHY6yh-d90266-Rd1e134">Tobias capitulo VI</ref> <quote xml:id="bHY6yh-d90266-Qd1e139">hii qui 
```

2024-09-28 14:10 UTC, jeffreycwitt commented on bHY6yh-d90266/cod-yyyiou_bHY6yh-d90266.xml
> +              <cb ed="#B" n="a"/>
```suggestion
              <cb ed="#C" n="a"/>
```

2024-09-28 14:10 UTC, jeffreycwitt commented on bHY6yh-d90266/cod-yyyiou_bHY6yh-d90266.xml
> +              <lb ed="#C"/>emin unusque suam habeat et unaqueque
```suggestion
              <lb ed="#C"/>enim uniusque suam habeat et unaque 
```

2024-09-28 14:10 UTC, jeffreycwitt commented on bHY6yh-d90266/cod-yyyiou_bHY6yh-d90266.xml
> +              § alia uero</ref> <quote xml:id="bHY6yh-d90266-Qd1e257">Vxores coruscantur
```suggestion
              § alia uero</ref> <quote xml:id="bHY6yh-d90266-Qd1e257">vxores coruscantur 
```

2024-09-29 20:30 UTC, GrantSchreib commented
file corrected

2024-10-11 00:35 UTC, jeffreycwitt approved these changes

2024-10-11 00:35 UTC, merged