P1 b1 r25 Paris
scta-texts/bHY6yh pull request #262
Opened 2023-07-01 17:11 UTC by GrantSchreib

2023-07-03 20:17 UTC, jeffreycwitt requested changes

2023-07-03 20:17 UTC, jeffreycwitt commented on bHY6yh-de6884/cod-bxxqqq_bHY6yh-de6884.xml
> +              et scribis et occidi et post
If this is the beginning of a new column, then there should also be the beginning of new line, no?

```suggestion
            <cb ed="#B" n="a"/>
            <lb ed="#B"/>et scribis et occidi et post 
```

2023-07-04 13:37 UTC, GrantSchreib commented
Completed

2023-07-11 16:25 UTC, jeffreycwitt approved these changes

2023-07-11 16:25 UTC, merged