P1 b1 r26 Paris
scta-texts/bHY6yh pull request #263
Opened 2023-07-01 19:40 UTC by GrantSchreib

2023-07-03 20:20 UTC, jeffreycwitt requested changes

2023-07-03 20:20 UTC, jeffreycwitt commented on bHY6yh-de7365/cod-bxxqqq_bHY6yh-de7365.xml
> +              <lb ed="#B"/>facite iusticiam coram deo creden<lb ed="#B" break="no"/>tes
Looks like you've lost your closing `</ref>` tag here which is making the XML invalid.
```suggestion
            <p xml:id="bHY6yh-de7365-d1e139">
              <lb ed="#B"/><ref xml:id="bHY6yh-de7365-Rd1e138">Thobie hystoria capitulo<!--line jumps up--> 13 et fideli</ref> <quote xml:id="bHY6yh-de7365-Qd1e143">Conuerti<!--line jumps down-->mini peccatores et 
              <lb ed="#B"/>facite iusticiam coram deo creden<lb ed="#B" break="no"/>tes 
```

2023-07-03 20:20 UTC, jeffreycwitt commented on bHY6yh-de7365/cod-bxxqqq_bHY6yh-de7365.xml
> +              <lb ed="#B"/><ref xml:id="bHY6yh-de7365-Rd1e153">MAlachias propheta capitulo 3</ref> <quote xml:id="bHY6yh-de7365-Qd1e156">Reuertimini adme
should probably be "ad me" 

```suggestion
              <lb ed="#B"/><ref xml:id="bHY6yh-de7365-Rd1e153">MAlachias propheta capitulo 3</ref> <quote xml:id="bHY6yh-de7365-Qd1e156">Reuertimini ad me 
```

2023-07-04 13:38 UTC, GrantSchreib commented
Corrected

2023-07-11 16:25 UTC, jeffreycwitt approved these changes

2023-07-11 16:26 UTC, merged