p1-b1-r32 Paris
scta-texts/bHY6yh pull request #277
Opened 2023-07-05 15:20 UTC by GrantSchreib

2023-07-11 16:40 UTC, jeffreycwitt approved these changes
I think there is a missing line break. If there is please fix, otherwise just confirm that there is no line break here and I will merge.

2023-07-11 16:40 UTC, jeffreycwitt commented on bHY6yh-de9144/cod-bxxqqq_bHY6yh-de9144.xml
> +          De christo et trinitate diuina Rubrica 32
are we missing a line break here?

2023-07-11 16:42 UTC, jeffreycwitt requested changes
need confirmation whether there is a missing line break at the beginning or not.

2023-07-13 13:33 UTC, GrantSchreib commented
corrected

2023-07-13 17:35 UTC, jeffreycwitt approved these changes

2023-07-13 17:35 UTC, merged