P1 b3 r4 Paris
scta-texts/bHY6yh pull request #345
Opened 2023-07-13 17:28 UTC by GrantSchreib

2023-07-13 17:41 UTC, jeffreycwitt requested changes

2023-07-13 17:41 UTC, jeffreycwitt commented on bHY6yh-d14568/cod-bxxqqq_bHY6yh-d14568.xml
> +          diligit</quote>
```suggestion
          <lb ed="#B"/>diligit</quote>
```

2023-07-13 17:41 UTC, GrantSchreib commented
corrected

2023-07-16 22:40 UTC, jeffreycwitt approved these changes

2023-07-16 22:41 UTC, merged