p1-b3-r13 Paris
scta-texts/bHY6yh pull request #361
Opened 2023-07-17 16:20 UTC by GrantSchreib

2023-07-18 14:25 UTC, jeffreycwitt requested changes

2023-07-18 14:25 UTC, jeffreycwitt commented on bHY6yh-d16692/cod-bxxqqq_bHY6yh-d16692.xml
> +      </div>
Edition references need to be changed.
```suggestion
      <div xml:id="starts-on">
        <pb ed="#B" n="22-v"/>
        <cb ed="#B" n="a"/>
      </div>
```

2023-07-19 13:14 UTC, GrantSchreib commented
corrected

2023-07-20 19:08 UTC, jeffreycwitt approved these changes

2023-07-20 19:08 UTC, merged