P2 b1 r1 Paris
scta-texts/bHY6yh pull request #380
Opened 2023-07-20 14:08 UTC by GrantSchreib

2023-07-20 19:39 UTC, jeffreycwitt requested changes

2023-07-20 19:39 UTC, jeffreycwitt commented on bHY6yh-d17907/cod-bxxqqq_bHY6yh-d17907.xml
> +          postea res et matura profectas
```suggestion
          <lb ed="#B"/>postea res et matura profectas 
```

2023-07-21 13:43 UTC, GrantSchreib commented
updated

2023-07-25 20:41 UTC, jeffreycwitt approved these changes

2023-07-25 20:42 UTC, merged