p2-b2-r3 Paris
scta-texts/bHY6yh pull request #428
Opened 2023-07-29 20:48 UTC by GrantSchreib

2023-08-04 19:38 UTC, jeffreycwitt requested changes

2023-08-04 19:38 UTC, jeffreycwitt commented on bHY6yh-d24602/cod-bxxqqq_bHY6yh-d24602.xml
> +          . Obsequi superant meretrix et pro<lb ed="#B" break="no"/>ditor
was this supposed to be a line break that accidentally became a `.`. Can you confirm?
```suggestion
          <lb ed="#B"/>Obsequi superant meretrix et pro<lb ed="#B" break="no"/>ditor 
```

2023-08-04 19:38 UTC, jeffreycwitt commented on bHY6yh-d24602/cod-bxxqqq_bHY6yh-d24602.xml
> +
Can we get rid of this extra empty line
```suggestion
```

2023-08-05 16:11 UTC, GrantSchreib commented
corrected

2023-08-08 00:45 UTC, merged