p2-b3-r14 Paris
scta-texts/bHY6yh pull request #496
Opened 2023-08-07 22:54 UTC by GrantSchreib

2023-08-08 00:51 UTC, jeffreycwitt requested changes

2023-08-08 00:51 UTC, jeffreycwitt commented on bHY6yh-d31897/cod-bxxqqq_bHY6yh-d31897.xml
> +              <lb ed="#B"/>constantior<quote>
closing quote tag got corrupted 

```suggestion
              <lb ed="#B"/>constantior</quote>
```

2023-08-08 23:59 UTC, GrantSchreib commented
corrected

2023-08-11 10:59 UTC, jeffreycwitt approved these changes

2023-08-11 10:59 UTC, merged