p2-b4-r1 Paris
scta-texts/bHY6yh pull request #497
Opened 2023-08-08 00:41 UTC by GrantSchreib

2023-08-11 11:00 UTC, jeffreycwitt requested changes

2023-08-11 11:00 UTC, jeffreycwitt commented on bHY6yh-d32366/cod-bxxqqq_bHY6yh-d32366.xml
> +              atque contraria</quote>
line break missing?

```suggestion
              <lb ed="#B"/>atque contraria</quote>
```

2023-08-12 13:53 UTC, GrantSchreib commented
corrected

2023-08-15 21:22 UTC, jeffreycwitt approved these changes

2023-08-15 21:22 UTC, merged