P2 b4 r2 Paris
scta-texts/bHY6yh pull request #503
Opened 2023-08-08 23:58 UTC by GrantSchreib

2023-08-11 11:38 UTC, jeffreycwitt requested changes

2023-08-11 11:38 UTC, jeffreycwitt commented on bHY6yh-d32659/cod-bxxqqq_bHY6yh-d32659.xml
> +              <lb ed="#B"/>quescit ¶ Tunc suus ex merito
```suggestion
              <lb ed="#B"/>quiescit ¶ Tunc suus ex merito 
```

2023-08-12 13:51 UTC, GrantSchreib commented
corrected

2023-08-15 21:24 UTC, jeffreycwitt approved these changes

2023-08-15 21:24 UTC, merged