p2-b4-r6 Paris
scta-texts/bHY6yh pull request #533
Opened 2023-08-12 15:10 UTC by GrantSchreib

2023-08-16 19:22 UTC, jeffreycwitt requested changes

2023-08-16 19:22 UTC, jeffreycwitt commented on bHY6yh-d33762/cod-bxxqqq_bHY6yh-d33762.xml
> +              iurgia conquiescunt verba sur<lb ed="#B" break="no"/>suronis
There error is here. You're missing the closing tag to this `<ref>`

```suggestion
              ¶ <ref xml:id="bHY6yh-d33762-Rd1e139">26 capitulo</ref> <quote>ignis et sursurone subtrac<lb ed="#B" break="no"/>to 
              iurgia conquiescunt verba sur<lb ed="#B" break="no"/>suronis 
```

2023-08-16 21:57 UTC, GrantSchreib commented
corrected

2023-08-17 13:44 UTC, jeffreycwitt approved these changes

2023-08-17 13:45 UTC, merged