p2-b4-r14 Paris
scta-texts/bHY6yh pull request #541
Opened 2023-08-12 21:26 UTC by GrantSchreib

2023-08-15 21:21 UTC, jeffreycwitt requested changes

2023-08-15 21:21 UTC, jeffreycwitt commented on bHY6yh-d35397/cod-bxxqqq_bHY6yh-d35397.xml
> +              <lb ed="#B"/>diebus & herodes autem viso ihesu
did you mean & here and throughout? or did you mean to use a pilcrow. 

& is a special character in XML, and therefore to write &, you have to write `&amp;`. 

But I haven't seen your manuscript use this character. Please double check.

2023-08-15 21:53 UTC, GrantSchreib commented
I do use that as my filler symbol, I forgot to replace them. It's been corrected.

2023-08-16 19:41 UTC, jeffreycwitt approved these changes

2023-08-16 19:41 UTC, merged