p2-b6-r5 Paris
scta-texts/bHY6yh pull request #580
Opened 2023-08-19 01:09 UTC by GrantSchreib

2023-08-25 11:52 UTC, jeffreycwitt requested changes
I think we are missing a few line break here

2023-08-25 11:52 UTC, jeffreycwitt commented on bHY6yh-d41894/cod-bxxqqq_bHY6yh-d41894.xml
> +              et tyranno Rubrica 5
are we missing a line break here?

2023-08-25 11:52 UTC, jeffreycwitt commented on bHY6yh-d41894/cod-bxxqqq_bHY6yh-d41894.xml
> +              dispotita in serui sed et quia
missing line break?

2023-08-25 11:52 UTC, jeffreycwitt commented on bHY6yh-d41894/cod-bxxqqq_bHY6yh-d41894.xml
> +              eum aut diligit quem metuit
missing line break?

2023-08-25 11:52 UTC, jeffreycwitt commented on bHY6yh-d41894/cod-bxxqqq_bHY6yh-d41894.xml
> +              regna perpetuo manent</quote>
missing line break?

2023-08-25 22:04 UTC, GrantSchreib commented
corrected

2023-08-28 17:56 UTC, jeffreycwitt approved these changes

2023-08-28 17:56 UTC, merged