p3-b1-r2 Paris
scta-texts/bHY6yh pull request #609
Opened 2023-08-23 21:13 UTC by GrantSchreib

2023-08-30 23:42 UTC, jeffreycwitt requested changes

2023-08-30 23:42 UTC, jeffreycwitt commented on bHY6yh-d46317/cod-bxxqqq_bHY6yh-d46317.xml
> +               <quote xml:id="bHY6yh-d46317-Qd1e127">Iuuenis inexpertus est eorum
are we missing a line break here?

2023-08-30 23:48 UTC, GrantSchreib commented
corrected

2023-09-06 23:24 UTC, jeffreycwitt approved these changes

2023-09-06 23:24 UTC, merged